"""empty message

Revision ID: 290bb92d8530
Revises: 9368c36ae035
Create Date: 2022-05-27 05:55:55.649375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '290bb92d8530'
down_revision = '9368c36ae035'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('start_tim', sa.DateTime(), nullable=True))
    op.drop_column('Show', 'start_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('start_time', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('Show', 'start_tim')
    # ### end Alembic commands ###
