"""empty message

Revision ID: 9368c36ae035
Revises: a02fb5852974
Create Date: 2022-05-27 05:46:41.623865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9368c36ae035'
down_revision = 'a02fb5852974'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Show', 'start_time',
               existing_type=sa.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Show', 'start_time',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
